

on:
  schedule:
    - cron: '0 0,12 * * *'
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: refresh-data

jobs:
  refresh-data:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install package for scan
        run: Rscript -e 'install.packages(c("here", "stringr"), repos = "https://cloud.r-project.org/")'


      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install XQuartz on macOS
        if: runner.os == 'macOS'
        run: brew install gdal

      - name: Install package installer
        run: Rscript -e 'install.packages(c("pak"), repos = "https://cloud.r-project.org/")'

      - name: Install package deps
        run: Rscript -e 'pak::pak(c("arrow", "vapour", "terra", "here", "rmarkdown",  "maps", "hypertidy/spatial.datasources"))'

      - name: Install bowerbird
        run: Rscript -e 'pak::pak(c("mdsumner/bowerbird@dry-run-list"))'

      - name: Install blueant
        run: Rscript -e 'pak::pak(c("AustralianAntarcticDivision/blueant"))'

      - name: Get update list
        run: Rscript -e 'source("data-raw/list_ice_files.R", echo = TRUE)'

      - name: Get Nuyina underway
        run: Rscript -e 'source("data-raw/get-underway.R", echo = TRUE)'



      - name: Commit
        run: |
          git config --global user.name 'Michael Sumner'
          git config --global user.email 'mdsumner@gmail.com'
          git add .
          git commit -m 'refreshing data' || echo "No changes to commit"
          git push || echo "No changes to commit"
