

on:
  schedule:
    - cron: '0 0,12 * * *'
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: refresh-data

jobs:
  refresh-data:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install package for scan
        run: Rscript -e 'install.packages(c("here", "stringr"), repos = "https://cloud.r-project.org/")'

      #- name: Scan
      #  run: Rscript -e 'source(here::here("data-raw", "scan.R"), echo = TRUE)'

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install XQuartz on macOS
        if: runner.os == 'macOS'
        run: brew install gdal

      - name: Install package installer
        run: Rscript -e 'install.packages(c("pak"), repos = "https://cloud.r-project.org/")'

      - name: Install package deps
        run: Rscript -e 'pak::pak(c("arrow", "vapour", "terra", "here", "rmarkdown",  "maps", "hypertidy/dsn"))'

     # - name: Install packages 2
    #    run: Rscript -e 'pak::pak(c("arrow", "archive", "assertthat", "aws.s3", "curl", "fs", "httr", "jsonlite", "lubridate", "magrittr", "methods", "openssl", "R.utils", "rmarkdown", "rvest", "stringr", "sys", "tibble", "xml2", "arrow"))'

      - name: Install bowerbird
        run: Rscript -e 'pak::pak(c("mdsumner/bowerbird@dry-run-list"))'

      - name: Install blueant
        run: Rscript -e 'pak::pak(c("AustralianAntarcticDivision/blueant"))'

      - name: Get data
        run: Rscript -e 'source("data-raw/get-data.R", echo = TRUE)'

      - name: Get update list
        run: Rscript -e 'source("data-raw/list_ice_files.R", echo = TRUE)'

      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: cleanup
        run: rm README.html



      - name: Commit
        run: |
          git config --global user.name 'Michael Sumner'
          git config --global user.email 'mdsumner@gmail.com'
          git add .
          git commit -m 'refreshing data' || echo "No changes to commit"
          git push || echo "No changes to commit"
