

on:
  schedule:
    - cron: ' 0   4,12,20   *   *   *'
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: render-doc

jobs:
  render-doc:
    runs-on: ${{ matrix.config.os }}
    ##container: mdsumner/hypertidy:main
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          #- {os: macos-latest,   r: 'release'}
          #- {os: windows-latest, r: 'release'}
          #- {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          #- {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      # - uses: r-lib/actions/setup-r@v2
      #   with:
      #     r-version: ${{ matrix.config.r }}
      #     http-user-agent: ${{ matrix.config.http-user-agent }}
      #     use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Get data
        run: Rscript -e 'source("R/sea_ice_png.R"); sea_ice_png()'

      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: cleanup
        run: rm README.html

      - name: Commit
        run: |
          git config --global --add safe.directory '*'
          git config --global user.name 'Michael Sumner'
          git config --global user.email 'mdsumner@gmail.com'
          git add .
          git commit -m 'render doc ' || echo "No changes to commit"
          git push || echo "No changes to commit"
