# on:
#   schedule:
#     - cron: '0 2,14 * * *'
#   push:
#     branches: [main, sentinel]
#   pull_request:
#     branches: [main]
#
# name: get-sentinel
#
# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     container: mdsumner/hypertidy:main
#     steps:
#       - uses: actions/checkout@v3
#
#       - run: |
#           source("data-raw/sentinel.R")
#         shell: Rscript {0}
#
#       - name: Commit
#         run: |
#           git config --global user.name 'Michael Sumner'
#           git config --global user.email 'mdsumner@gmail.com'
#           git config --global --add safe.directory '*'
#           git add data-raw/sentinel-image.tif
#           git commit -m 'commit new sentinel image' || echo "No changes to commit"
#           git push || echo "No changes to commit"
#
