# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 2,14 * * *'
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: get-sentinel

jobs:
  docker:
    runs-on: ubuntu-latest
    container: rocker/geospatial:dev-osgeo
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install package for scan
        run: Rscript -e 'install.packages(c("here", "stringr"), repos = "https://cran.rstudio.com/")'


      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install package installer
        run: Rscript -e 'install.packages(c("pak"), repos = "https://cran.rstudio.com/")'

      - name: Install package deps
        run: Rscript -e 'pak::pak(c("arrow",   "terra", "sf"))'


      - name: Get data
        run: Rscript -e 'source("data-raw/sentinel.R", echo = TRUE)'

      - name: Commit
        run: |
          git config --global user.name 'Michael Sumner'
          git config --global user.email 'mdsumner@gmail.com'
          git add .
          git commit -m 'render doc ' || echo "No changes to commit"
          git push || echo "No changes to commit"
