# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 2,14 * * *'
  push:
    branches: [main, sentinel]
  pull_request:
    branches: [main]

name: get-sentinel

jobs:
  docker:
    runs-on: ubuntu-latest
    container: rocker/geospatial
    steps:
      - uses: actions/checkout@v3

      - run: Rscript -e 'install.packages(c("pak"), repos = "https://cran.rstudio.com/")'

      - run: Rscript -e 'pak::pak(c("hypertidy/dsn"))'

      - run: |
          source("data-raw/sentinel.R")
        shell: Rscript {0}

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: file.tif
