

on:
  schedule:
    - cron: '0 0,12 * * *'
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: test-dep

jobs:
  test-dep:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true


      - uses: r-lib/actions/setup-pandoc@v2


      - name: Install package installer
        run: Rscript -e 'install.packages(c("pak"), repos = "https://packagemanager.posit.co/cran/__linux__/focal/latest")'

      - name: Install package deps
        run: Rscript -e 'install.packages(c("arrow", "vapour", "terra", "here", "rmarkdown",  "maps"), repos = "https://packagemanager.posit.co/cran/__linux__/focal/latest")'


      - name: Commit
        run: |
          git config --global user.name 'Michael Sumner'
          git config --global user.email 'mdsumner@gmail.com'
          git add .
          git commit -m 'refreshing data' || echo "No changes to commit"
          git push || echo "No changes to commit"
